### ISSUE TITLE
System suddenly crashes

### ISSUE THREAD

**Issue by HOURAI-K** [opa334/Dopamine#160] opened 2023-05-12 02:19 UTC
The device suddenly goes to a black screen and reboots.
Rebootting while using Chrome, rebooting when touch in the App Library icon, etc... is **REALLY RANDOM**.

However, since the reboot does **NOT occur when using cellular data**, the crash is most likely caused by Wi-Fi.

[panic-full-2023-05-12-104824.000.log](https://github.com/opa334/Dopamine/files/11458240/panic-full-2023-05-12-104824.000.log)
[ExcUserFault_wifid-2023-05-12-104901.log](https://github.com/opa334/Dopamine/files/11458266/ExcUserFault_wifid-2023-05-12-104901.log)

**Comment by Cryptiiiic** [comment] 2023-05-12 03:55
Known issue, duplicate of many, not planned

**Closed by Cryptiiiic** 2023-05-12 03:55 UTC
Labels: bug, wontfix, solved
