### ISSUE TITLE
Random Reboots + Brightness

### ISSUE THREAD

**Issue by F1zzyD** [opa334/Dopamine#234] opened 2023-07-20 16:37 UTC
Using Dopamine 1.1.2 with iPhone 12 Pro on iOS 15.4.1

After a successful jailbreak and reboot of userspace, brightness is so low that I am unable to see the screen. I can sometimes manage to get to the Dopamine app to restoring and the brightness fixes itself, however I must mind a VERY dark room to see the screen.

After about 2-4 hours after a successful jailbreak, the phone will randomly reboot back to stock iOS. The phone can be playing media, browsing an app/internet, or simply in sleep mode, yet it will panic and reboot. This has been tested with and without tweaks installed. I'm averaging about 3-4 reboots a day.

**Comment by lukar-debug** [comment] 2023-07-21 00:32
Does this happen when on stock iOS (no jailbreak)

**Comment by F1zzyD** [comment] 2023-07-21 01:31
> Does this happen when on stock iOS (no jailbreak)

Haven't tested stock, but I'll give that's go tomorrow and will report back.

**Comment by opa334** [comment] 2023-10-24 11:13
First one is known bug on A14

For the second one, send a panic log???

**Comment by opa334** [comment] 2023-10-24 11:39
So I'm guessing first one is duplicate of #123

Second one might be duplicate of #274, although the fact it happens without tweaks sounds weird.

**Closed by opa334** 2023-10-24 11:39 UTC
