### ISSUE TITLE
Dopamine 2 does not detect the camera in

### ISSUE THREAD

**Issue by JimneGt** [opa334/Dopamine#384] opened 2024-02-19 01:21 UTC
I was able to verify that this jailbreak dopamine 2, at the time of installation in all the tweaks, does work without any problem, despite its exclusive versions for iOS 15.x and they work wonderfully on my iPhone X with iOS 16.5.1, but Unfortunately it does not detect or completely disable the camera.

**Comment by opa334** [comment] 2024-02-19 12:12
Duplicate of #339

**Closed as not planned by opa334** 2024-02-19 12:12 UTC
