### ISSUE TITLE
Termius crash on launch.

### ISSUE THREAD

**Issue by midkin** [opa334/Dopamine#155] opened 2023-05-10 22:06 UTC
After jailbreaking with Dopamine 1.0.4 the "Termius" app from AppStore crashes on launch.

Any solutions?

App url:
https://apps.apple.com/gr/app/termius-terminal-ssh-client/id549039908

**Comment by opa334** [comment] 2023-05-11 01:05
Duplicate of #139

**Closed by opa334** 2023-05-11 01:05 UTC

**Comment by ilizhu** [comment] 2023-05-11 01:07
Install the Choicy Tweak  from "[opa334's Repo](https://opa334.github.io)" and disable tweak injection into the "Termius" app
