### ISSUE TITLE
Phone freezes on Lock Screen after jailbreak with dopamine.

### ISSUE THREAD

**Issue by derek295** [opa334/Dopamine#98] opened 2023-05-03 17:08 UTC
I can’t enable tweak injection in dopamine. Every time I do my device freezes on lockscreen after user space reboot. I’m on 13 pro 15.0.1. I’ve already updated to version 1.0.1 of dopamine. I've done the following steps:

1. Re-install Dopamine environment (via erase jailbreak)

2. Install only ellekit and Amber tweak to test

3. Disable tweak injection. (No issues, until I re-enable tweaks and perform user space reboot).

**Comment by opa334** [comment] 2023-05-03 17:19
Duplicate of #86?

**Comment by derek295** [comment] 2023-05-03 17:24
> Duplicate of #86?

Not duplicate (I don't think, at least not to me), but very similar. I disable wifi beforehand and still the same issue (freezing on Lock Screen). I've noted however sometimes after jailbreaking with tweaks enabled I can unlock the screen after attempting to force reset device last second the device will unlock and carry out any button presses while screen was frozen. Settings app does not open (opens, but only has black screen).

**Comment by opa334** [comment] 2023-05-03 17:32
Test again in 1.0.2.

**Comment by derek295** [comment] 2023-05-03 17:40
> Test again in 1.0.2.

Tested I'm reporting everything seems to run fine now. No freezing and can install new tweaks and user space reboot without a problem. Thank you.

**Closed** 2023-05-03 18:36 UTC
