### ISSUE TITLE
iPhone 6s Camera doesn't work in jailbroken mode

### ISSUE THREAD

**Issue by iika18** [opa334/Dopamine#396] opened 2024-02-20 12:43 UTC
iOS 15.8.1
Installed using Trollstore, dopamine latest version
When i jailbreak everything goes correctly but when i open camera or camera in any other app it is completely black even to it isn't covered but when i reboot into unjb mode it works flawlessly. I haven't had this issue with meowbrek.

**Comment by eglacias** [comment] 2024-02-20 23:20
Duplicate of number [339](https://github.com/opa334/Dopamine/issues/339#issue-2139922209), check out that thread there are solutions

**Closed as not planned** 2024-02-21 00:03 UTC
