### ISSUE TITLE
Device brightness is lower than normal after jailbreaking

### ISSUE THREAD

**Issue by sshrmr** [opa334/Dopamine#223] opened 2023-07-09 07:26 UTC
Im using iPhone 12 Pro Max 15.4.1.
After a successful jailbreak, the device brightness is super low that i can barely see anything (even tho its set on maximum in control center). I always have to respring after jailbreaking to fix this.

happens on 1.0.5 and still not fixed on 1.1.1

**Comment by Aftended** [comment] 2023-07-09 08:30
Lol, same to me on iPhone 13 Pro Max 15.0.2 dopamine

**Comment by opa334** [comment] 2023-10-24 11:37
Duplicate of #123

**Closed by opa334** 2023-10-24 11:37 UTC
