### ISSUE TITLE
Broken on IOS 16 Beta

### ISSUE THREAD

**Issue by Lunariansia** [opa334/Dopamine#561] opened 2024-05-06 18:48 UTC
It fails to pathfind on IOS 16 beta with an error about symbols, though I can't remember the exact error whilst typing this. I hope a bug fix for it can be found.

**Comment by opa334** [comment] 2024-05-06 19:02
Please include your device and exact version.

**Comment by Lunariansia** [comment] 2024-05-06 20:06
Device: Ipad Gen 7
Version: 16.0 Beta (20A5283p)

**Comment by aydenbottos** [comment] 2024-05-07 06:30
Same issue as #329 unfortunately

**Comment by opa334** [comment] 2024-05-07 10:49
Yes, duplicate of #329

**Closed as not planned by opa334** 2024-05-07 10:49 UTC
