### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lzxssg** [opa334/Dopamine#167] opened 2023-05-13 09:09 UTC
![07CE33C8-8E07-4FFF-88DA-39617426BF70](https://github.com/opa334/Dopamine/assets/106219106/54932e27-3fa2-4e40-9f70-db55e039ac2c)
![4A8BA211-D8B1-492B-948C-7BFF5792CA9F](https://github.com/opa334/Dopamine/assets/106219106/38c945da-501b-412a-a537-5f6d694c3fef)

**Comment by lzxssg** [comment] 2023-05-13 09:11
Now you can't jailbreak with the previous version
a15 13pm ios15.4.1

**Comment by Liam0205** [comment] 2023-05-13 11:17
reboot and try again

**Comment by opa334** [comment] 2023-05-13 18:27
duplicate of #162

**Closed by opa334** 2023-05-13 18:27 UTC
