### ISSUE TITLE
Using Bluetooth earphones raises the possibility of experiencing kernel crashes.

### ISSUE THREAD

**Issue by invalidunit** [opa334/Dopamine#161] opened 2023-05-12 03:36 UTC
When connecting Bluetooth earphones (such as AirPods), the probability of experiencing a kernel crash increases. Several of my friends have had their devices suddenly restart while wearing earphones and listening to music. 
Here is the log of my crash.
[panic-full-2023-05-12-090803.000.ips.txt](https://github.com/opa334/Dopamine/files/11458649/panic-full-2023-05-12-090803.000.ips.txt)

**Comment by Cryptiiiic** [comment] 2023-05-12 03:54
Duplicate of #152

**Closed by Cryptiiiic** 2023-05-12 03:54 UTC
Labels: duplicate

**Comment by invalidunit** [comment] 2023-05-12 04:04
> Duplicate of #152

However, their issue involved entering safe mode, while my problem is a kernel crash and subsequent restart, so I don't think it's the same problem.

**Comment by Cryptiiiic** [comment] 2023-05-12 04:12
even if its not, spinlock panic is not a planned fix
