### ISSUE TITLE
VPN and TrollStore doesn't work on iOS 16.6 A11

### ISSUE THREAD

**Issue by onmyodev** [opa334/Dopamine#465] opened 2024-02-28 12:57 UTC
It seems that after jailbreaking with Dopamine 2.0.8 I cannot connect to the VPN, regardless of whether it is connected or not when jailbreaking. Device model is iPhone10,1 from CN mainland, iOS 16.6.

Moreover, TrollStore and the persisitence helper failed to load after jailbreaking. They are installed via the latest version of TrollStar.

**Comment by opa334** [comment] 2024-02-28 18:08
1. As I already stated, it works fine for me on iPhone X, 16.6
2. once again, duplicate of #454

**Closed as not planned by opa334** 2024-02-28 18:08 UTC
