### ISSUE TITLE
Touch not working after dopamine (Iphone 8, 15.6.1

### ISSUE THREAD

**Issue by Random00gg** [opa334/Dopamine#343] opened 2024-02-17 11:40 UTC
After jailbreaking with dopamine (tried 2.00 and 2.04) and after that (after the phone kinda restarts) touch doesnt work, I have to force restart to get it back but not jailbroken anymore.

**Comment by SternXD** [comment] 2024-02-17 18:31
I have the same issue on my iPhone 8 on 16.6 Beta 1 and I've tried to troubleshoot for hours it seems to be an issue with replacing the display **_though other jailbreaks work and it works while I am unjailbroken_**

**Comment by opa334** [comment] 2024-02-19 12:24
Duplicate of #296

**Closed as not planned by opa334** 2024-02-19 12:24 UTC
