### ISSUE TITLE
Battery loading and nothing show

### ISSUE THREAD

**Issue by Bob4716** [opa334/Dopamine#359] opened 2024-02-17 20:54 UTC
I find bug right now, the battery log loading and loading and nothing show.

![image](https://github.com/opa334/Dopamine/assets/96495576/9ade82fe-0d9f-4f3a-8145-c0008f03f391)

**Comment by Bob4716** [comment] 2024-02-17 20:58
I recorded a video for more explanation the problem.

https://github.com/opa334/Dopamine/assets/96495576/b71e1b38-b356-4b93-8930-fa97a739386b

I wait max 4+ minutes but nothing happen.

**Comment by TheDoctor200** [comment] 2024-02-17 21:17
Same here

**Comment by opa334** [comment] 2024-02-19 12:25
What device / version is this? This is most likely a tweak issue

**Comment by korboybeats** [comment] 2024-02-20 07:58
> What device / version is this? This is most likely a tweak issue

I have a 13 Pro Max on iOS 15.0. My battery settings is telling me I have a non genuine battery. This phone has never had any parts replaced.

![890F2850-C165-40FE-99CE-4B0E70D0D3D6](https://github.com/opa334/Dopamine/assets/80824905/29c370d8-788c-4f5a-a3aa-32c7bcc6831a)

I checked the battery settings in jailed mode which it never loads. The loading circle spins infinitely, but it does not say non genuine part this time.

![547414C0-68CA-4C35-B28F-BBF5FF7F04F8](https://github.com/opa334/Dopamine/assets/80824905/82a821db-730a-40b0-8636-4aceb7c3dc7d)

**Comment by BBBKyleBBB** [comment] 2024-02-20 19:18
It does look like this is a tweak issue, when starting from a fresh dopamine 2 jailbreak, the graph does populate.

**Comment by bewl87** [comment] 2024-02-20 19:18
this is happening on my iphone x on 16.6.1 too, loads battery data fine when rebooted into jailed state. i've tried uninstalling my tweaks individually to find the culprit but no luck. not that important tho the jailbreak is working perfect probably the most stable one i've used yet. i remember this issue happening on 13.3 using unc0ver had to disable loading tweaks with choicy can't remember what in tho

**Comment by Bob4716** [comment] 2024-02-20 19:21
> What device / version is this? This is most likely a tweak issue

I have iPhone X ios 16.1 dopamine 2.0.5

**Comment by BBBKyleBBB** [comment] 2024-02-20 19:35
for me the issue is with preference loader:
PreferenceLoader - sileo://package/preferenceloader - from https://apt.procurs.us/dists/1900
as soon as this tweak is removed, the chart populates again.

**Comment by Bob4716** [comment] 2024-02-20 19:47
> for me the issue is with preference loader:
> 
> PreferenceLoader - sileo://package/preferenceloader - from https://apt.procurs.us/dists/1900
> 
> as soon as this tweak is removed, the chart populates again.

Okay but how to unistall is show me this error, I try uninstall or reinstall but don't work.

![image](https://github.com/opa334/Dopamine/assets/96495576/5ace0cc6-d749-4758-b10f-605c44992b1a)

Maybe uninstall manually but how?

**Comment by BBBKyleBBB** [comment] 2024-02-20 19:53
I'm unfortunately not sure- you just may want to uninstall the dopamine jailbreak entirely and rejailbreak.

**Comment by Bob4716** [comment] 2024-02-20 19:55
> I'm unfortunately not sure- you just may want to uninstall the dopamine jailbreak entirely and rejailbreak.

Okay I try later thanks you

**Comment by opa334** [comment] 2024-02-20 20:41
Maybe do what it tells you and refresh sources?

Besides, I don't think uninstalling PreferenceLoader is something you should do.

**Comment by bewl87** [comment] 2024-02-20 20:43
> Maybe do what it tells you and refresh sources?
> 
> Besides, I don't think uninstalling PreferenceLoader is something you should do.

i think when you select the hide jailbreak option in dopamine it throws an error like that, it happened to me earlier when i tried to uninstall something

**Comment by opa334** [comment] 2024-02-20 20:56
> > Maybe do what it tells you and refresh sources?
> > Besides, I don't think uninstalling PreferenceLoader is something you should do.
> 
> i think when you select the hide jailbreak option in dopamine it throws an error like that, it happened to me earlier when i tried to uninstall something

Of course it does. The jailbreak is only meant to be hidden for a short period of time so you can open an app with jailbreak detection.

**Comment by BBBKyleBBB** [comment] 2024-02-20 21:51
Yep, my point with uninstalling PreferenceLoader was just that it was tweak related, and not jailbrak related.  As you will need PreferenceLoader, you could also install Choicy and turn on an option to launch the settings app without tweaks.  This way you can view the battery information when launching the Settings app without tweaks, and when launching the Settings app normally, will be able to view your tweaks in Settings, but not the Battery information.

**Comment by korboybeats** [comment] 2024-02-20 23:46
> Yep, my point with uninstalling PreferenceLoader was just that it was tweak related, and not jailbrak related. As you will need PreferenceLoader, you could also install Choicy and turn on an option to launch the settings app without tweaks. This way you can view the battery information when launching the Settings app without tweaks, and when launching the Settings app normally, will be able to view your tweaks in Settings, but not the Battery information.

It definitely is jailbreak related because I have never had this issue with Dopamine 1, Xina 1, or Xina 2.

**Comment by opa334** [comment] 2024-02-21 00:04
This issue seems exclusive to arm64 for that matter.

**Comment by korboybeats** [comment] 2024-02-21 00:15
Well now I uninstalled the jailbreak and I'm still getting the non genuine message.

**Comment by opa334** [comment] 2024-02-21 00:23
> Well now I uninstalled the jailbreak and I'm still getting the non genuine message.

Maybe someone broke into your house and switched the battery while you were asleep?

**Comment by korboybeats** [comment] 2024-02-21 00:26
haha so funny

**Comment by korboybeats** [comment] 2024-02-21 00:42
It's all good, I fixed it.

**Comment by Bob4716** [comment] 2024-02-21 15:35
> I'm unfortunately not sure- you just may want to uninstall the dopamine jailbreak entirely and rejailbreak.

I try reinstalling dopamine but I can't uninstall any tweak :/ and refreshing source don't work, hide jailbreak broke Sileo and zebra. And now I can't uninstall/install anything (tweak) maybe one tweak broke my sileo and zebra? Yes hide jailbreak work for battery but don't work for my bank app :/ 

I try reinstalling packages but I don't know which ones of tweak broke my sileo and zebra and I worry it's happening again :/ maybe new update fix this issue but it'll have to do for now. Thank you very much oppa and everyone who try or helped me I appreciate that.

**Comment by Bob4716** [comment] 2024-02-21 15:36
Hide jailbreak fix this issue, hide jail and battery log show so I close this issue.

**Comment by opa334** [comment] 2024-02-21 17:04
that's not an appropiate fix

**Comment by BBBKyleBBB** [comment] 2024-02-21 18:25
> > I'm unfortunately not sure- you just may want to uninstall the dopamine jailbreak entirely and rejailbreak.
> 
> I try reinstalling dopamine but I can't uninstall any tweak :/ and refreshing source don't work, hide jailbreak broke Sileo and zebra. And now I can't uninstall/install anything (tweak) maybe one tweak broke my sileo and zebra? Yes hide jailbreak work for battery but don't work for my bank app :/
> 
> I try reinstalling packages but I don't know which ones of tweak broke my sileo and zebra and I worry it's happening again :/ maybe new update fix this issue but it'll have to do for now. Thank you very much oppa and everyone who try or helped me I appreciate that.

Hi Bob, just to clarify, when you hide the jailbreak in the Dopamine app, Sileo and Zebra will not open.  When you unhide the jailbreak, they will open again.  In one of my previous replies, I mentioned another avenue you can go, installing the tweak Choicy, and setting the option for the settings app to be launched without tweaks.  This will allow the battery information to show as expected when tweaks are ignored, and to see the tweaks as normal when the option is not used to open the Settings app.

**Comment by bewl87** [comment] 2024-02-21 19:57
for me disable tweak injection in settings is grayed out in choicy ![image](https://github.com/opa334/Dopamine/assets/49694850/9a86925a-6db4-4f54-b05c-ef1315d47eed)

**Comment by Haeckli** [comment] 2024-02-21 20:24
I see the exact same behavior even on palera1n jailbroken devices as soon as having Poomsmart's "EmojiFontManager" being installed. Disabling this tweak with iCleaner Pro makes the battery-display work again... 
So, I doubt it's connected to Dopamine...

**Comment by BBBKyleBBB** [comment] 2024-02-21 20:34
> for me disable tweak injection in settings is grayed out in choicy ![image](https://private-user-images.githubusercontent.com/49694850/306757591-9a86925a-6db4-4f54-b05c-ef1315d47eed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDc3MjcsIm5iZiI6MTcwODU0NzQyNywicGF0aCI6Ii80OTY5NDg1MC8zMDY3NTc1OTEtOWE4NjkyNWEtNmRiNC00ZjU0LWIwNWMtZWYxMzE1ZDQ3ZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDIwMzAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OGNlY2Y2N2M0MDlmZDU2OWUzNWVlMDEzOTFkZDIzMjhlOGQ5OGY4MWExZWEyNjdhNDAwZjNkYWY2MzcyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e8_lqcO3joLYR-P3hhQIHhGoMob7YGJxGpSdQBHGDAg)

Right, but what you can do is this:
![IMG_0359](https://github.com/opa334/Dopamine/assets/79493153/1845b578-1174-4126-a6df-8535a5854c17)
and 3d or haptic touch settings and select "Launch without tweaks"
![IMG_0360](https://github.com/opa334/Dopamine/assets/79493153/94a5bae6-9bd5-44b4-ab16-f6fdeb4f2d34)

**Comment by kok3shidoll** [comment] 2024-02-22 21:26
It appears that CS_VALID was cleared from the csflag of the powerlogHelperd process and it terminated.  so only arm64(-A11) devices are affected. This appears to be a similar issue to the previous failure of emojiport to work with jailbreaks such as meowbrek2.

**Comment by opa334** [comment] 2024-02-23 17:57
Should be fixed in latest nightly:
https://github.com/opa334/Dopamine/actions/runs/8023037614/artifacts/1270506846

Please test!

**Comment by bewl87** [comment] 2024-02-23 18:08
can confirm battery info now loading on iphone x 16.6.1 👌😁

**Comment by bewl87** [comment] 2024-02-23 18:28
https://github.com/opa334/Dopamine/assets/49694850/137784fe-6ed9-4b8b-97a3-dbe083af41a3

**Closed as completed** 2024-02-23 19:05 UTC

**Comment by sanmiguel71** [comment] 2024-02-24 13:02
you are a genius, work perfekt on iPhone 6s, 15.8

**Comment by iBilly86** [comment] 2025-11-24 20:52
How do you fixit!
