### ISSUE TITLE
Device won’t have Internet access if device is connected to a VPN while jail breaking.

### ISSUE THREAD

**Issue by ghost** [opa334/Dopamine#429] opened 2024-02-24 11:23 UTC
If a VPN connection is enabled while jail breaking, internet will not be accessible in the jailbroken state. If you may, please might you add a disable vpn feature just like the Wi-Fi disable, before the process starts.

**Comment by opa334** [comment] 2024-02-24 12:06
Can't reproduce, works fine for me.

**Comment by boli2017** [comment] 2024-02-27 10:21
> Can't reproduce, works fine for me.

I can open the vpn at first, but after using it for a while, I can’t open the vpn. The latest version of dopamine. IOS16.6 A11

**Comment by opa334** [comment] 2024-03-12 04:30
Fixed in 2.0.10+

**Closed as completed** 2024-03-12 04:30 UTC
