### ISSUE TITLE
arm64: Camera not working

### ISSUE THREAD

**Issue by eglacias** [opa334/Dopamine#339] opened 2024-02-17 09:50 UTC
Unjailbreak reboot and camera fine
blacks out after 5 secs on dopamine 2.0.4
iPhone 6s Plus iOS 15.8
Palerain for months then just rebooted and TrollStore installed dopamine and rebuild tweaks from scratch, copy in prefs from palerain prefs

btw already got one full reboot panic or whatever. 

But all tweaks work and jailbreak works every time!

**Comment by Thyssenkrupp234** [comment] 2024-02-17 17:18
Install choicy, and disable tweak injection into Camera.

**Comment by eglacias** [comment] 2024-02-17 22:21
Oh of course. Camera comes back and all other camera apps which stopped then work fine too after Choicy installed and disable only iOS camera app and its CameraMessagesApp app plugin.

it’s a good workaround Since I have no tweaks that I can’t live without on the camera, though it looks like other people are having weird issues of the same type with camera too.

**Comment by eglacias** [comment] 2024-02-17 22:30
. Weird. I had spring +11 disable black bars on camera turning that off didn’t change anything, disabling tweak and Jackson caused it to come back. Now re-enabling the tweak injection and re-enabling the black bars and the camera functions properly again.

Reboot to unjailed broken and the camera took forever on a black screen to load up. Went back to springboard and launch the camera again, a little bit of black screen then I switch to front facing camera and it came on and then switched to the back facing camera and it came on.

jail broke again left the Tweakinjection and everything as it was, camera did the same thing except this time stayed on black screen, minimized, open the Camera app up again and after a few seconds it came up normal and remained that way.

**Comment by eglacias** [comment] 2024-02-18 02:18
So far without changing anything and turning everything back off (enable all tweak injection) in choicy, the camera with the springplus11 hide top and bottom bars setting, all just works again.

What seems to be consistent so far is when the stock camera app stopped working so did any application with access to the camera.

Funny how someone else had an issue with a message about camera hardware being replaced all the sudden. 

I’ll see if it comes up again and then try picking off tweaks one by one and see if I can find anything.

**Comment by opa334** [comment] 2024-02-23 17:58
Might be fixed in latest nightly, please test
https://github.com/opa334/Dopamine/actions/runs/8023037614/artifacts/1270506846

**Comment by Thyssenkrupp234** [comment] 2024-02-23 19:17
disabled choicy and camera works

**Comment by opa334** [comment] 2024-02-23 19:26
@kjutzn @JimneGt @eglacias

please test the build I posted!

**Comment by JimneGt** [comment] 2024-02-23 21:25
thanks opa it really worked for me....you are a hero

**Comment by eglacias** [comment] 2024-02-23 21:34
You mean disabled camera *in* choicy not disable choicy (in icleaner) I’m guessing. 

Btw I’ve got 6 days uptime and counting so won’t be rebooting my phone to try to break camera again until I get a reboot! Haven’t had it go black screen since the disable then reenable same tweaks. IE I have nothing disabled in choicy, same tweaks running as when the problem happened. 

Makes me think it wasn’t a tweak but some weird jailbreak problem near the jailbreak userspace reboot time, perhaps the bad total panic reboot I got too as that happened soon after rejailbreaking, on release day 1… 

I’ll run that build if I get a reboot or camera problem again.

**Comment by opa334** [comment] 2024-02-23 22:02
> disabled choicy and camera works

You mean you disabled the "Disable Tweak Injection" toggle of Choicy and it still works, right?

**Comment by Thyssenkrupp234** [comment] 2024-02-23 23:36
> You mean disabled camera _in_ choicy not disable choicy (in icleaner) I’m guessing.
> 
> Btw I’ve got 6 days uptime and counting so won’t be rebooting my phone to try to break camera again until I get a reboot! Haven’t had it go black screen since the disable then reenable same tweaks. IE I have nothing disabled in choicy, same tweaks running as when the problem happened.
> 
> Makes me think it wasn’t a tweak but some weird jailbreak problem near the jailbreak userspace reboot time, perhaps the bad total panic reboot I got too as that happened soon after rejailbreaking, on release day 1…
> 
> I’ll run that build if I get a reboot or camera problem again.

No, I disabled choicy. Before, the issue was fixed by disabling camera tweak injection in choicy. Since I assumed this build fixed it, I turned off “disable tweak injection” on camera, and the issue is fixed.

**Comment by Thyssenkrupp234** [comment] 2024-02-23 23:36
> > disabled choicy and camera works
> 
> You mean you disabled the "Disable Tweak Injection" toggle of Choicy and it still works, right?

Yes, correct. Works great

**Comment by opa334** [comment] 2024-02-23 23:51
Alright seems that the issue is fixed then.

**Closed as completed by opa334** 2024-02-23 23:51 UTC

**Comment by eglacias** [comment] 2024-02-24 00:14
Problem is, it works great with me with the 2.06 build and the exact build that had the problem as I stated above and further above on day 1. 
In other words I have not installed this test build and have not had the camera issue come back up. Therefore the issue *appears* to be “solved” with the same build that caused the problem.

**Comment by eglacias** [comment] 2024-02-24 00:16
I have the test build, and if the issue comes back up without it IE with the 2.06 I have now or with any other regular update I will post it again

**Comment by iika18** [comment] 2024-02-24 18:39
Awesome it is now working on my 6s
