### ISSUE TITLE
iPhone 6s touch not working

### ISSUE THREAD

**Issue by nerdydumbykier** [opa334/Dopamine#651] opened 2024-09-23 16:16 UTC
Device: iPhone 6s
iOS; 15.8.3
Dopamine Version: 2.2.2

So, I was trying out Dopamine for the first time and it worked okay. However, once I do a userspace reboot, the phone touchscreen becomes unresponsive. Everything works EXCEPT the touchscreen. This renders the phone useless and I can't force restart it because the home button is broken. HOWEVER, the touch does come back after like 10-20 minutes of waiting.

The touch works perfectly fine unjailbroken even after a restart. I want to also clarify that my screen was replaced before jailbreaking at first. If relevant to this case, my battery health is 68%.
I did try "reinstalling" Dopamine and setting the jetsam thingy but no luck.

Thanks.

**Comment by F1248** [comment] 2024-09-23 17:02
> If your device has a replacement screen, there is a chance (especially if the screen is of low quality) that the touchscreen will not work after userspace rebooting into a jailbroken state. This is not a Dopamine issue, and can only be fixed by getting a better screen replacement.

https://ios.cfw.guide/installing-dopamine/#installing-dopamine

**Comment by opa334** [comment] 2024-09-23 19:12
Duplicate of #296

Although the fact it does work again after 10-20 minutes is interesting, never heard of that before.

**Closed as not planned by opa334** 2024-09-23 19:12 UTC
