### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by OverWatch-R** [opa334/Dopamine#576] opened 2024-05-18 18:22 UTC
Battery Health doesn’t show up in settings

**Comment by robi62** [comment] 2024-05-20 17:21
I have same problem on my iph11 pro iOS 16.3.1 now it does not even show when I boot in stock mode

**Comment by luhgarlicbread** [comment] 2024-06-12 15:50
Bro me too:
iPhone 11 16.3.1

**Comment by robi62** [comment] 2024-06-12 18:21
The only thing there is a tweak which will show heath in control centre
![33361F2D-5B0F-4456-BC79-AD2E0819C63E](https://github.com/opa334/Dopamine/assets/48402851/10817404-7447-4d7f-94ec-03a3fc63e20a)

**Comment by opa334** [comment] 2024-06-12 19:36
> I have same problem on my iph11 pro iOS 16.3.1 now it does not even show when I boot in stock mode

If it doesn't show up in stock mode, it's not caused by Dopamine!

**Comment by robi62** [comment] 2024-06-12 20:08
Hi before I jaibreak iphone 11 pro it was showing but since I jb not showing even in stock mode
I am tempted to do a erase and reset and see  
But frightened to loose all tweaks

**Comment by opa334** [comment] 2024-06-12 20:28
> Hi before I jaibreak iphone 11 pro it was showing but since I jb not showing even in stock mode I am tempted to do a erase and reset and see But frightened to loose all tweaks

you probably just disabled a daemon or something, that can easily be undone without resetting your device.

**Comment by robi62** [comment] 2024-06-12 20:42
I wish I knew what to look for..

**Comment by luhgarlicbread** [comment] 2024-06-13 02:30
> The only thing there is a tweak which will show heath in control centre
> ![33361F2D-5B0F-4456-BC79-AD2E0819C63E](https://private-user-images.githubusercontent.com/48402851/339086496-10817404-7447-4d7f-94ec-03a3fc63e20a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDYxMTEsIm5iZiI6MTcxODI0NTgxMSwicGF0aCI6Ii80ODQwMjg1MS8zMzkwODY0OTYtMTA4MTc0MDQtNzQ0Ny00ZDdmLTk0ZWMtMDNhM2ZjNjNlMjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAyMzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZWFlNWMyM2M2YjA4MzFmMjQ4ZjY3ZTE3NjQ5NTFiNWE4YWJkZWNlNmIwNTIwOTliNWViNmMwY2Y2YmI4YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d4TXqOxe45nwbL5qgA3o4x6dBLWo409An5MwTWTNFOk)

What is the tweak?

**Comment by luhgarlicbread** [comment] 2024-06-13 02:30
> > Hi before I jaibreak iphone 11 pro it was showing but since I jb not showing even in stock mode I am tempted to do a erase and reset and see But frightened to loose all tweaks
> 
> you probably just disabled a daemon or something, that can easily be undone without resetting your device.

How do we re-enable it?

**Comment by opa334** [comment] 2024-06-13 08:06
You enable it the same way you disabled it, presumably

**Comment by robi62** [comment] 2024-06-13 08:18
> > The only thing there is a tweak which will show heath in control centre
> > ![33361F2D-5B0F-4456-BC79-AD2E0819C63E](https://private-user-images.githubusercontent.com/48402851/339086496-10817404-7447-4d7f-94ec-03a3fc63e20a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDYxMTEsIm5iZiI6MTcxODI0NTgxMSwicGF0aCI6Ii80ODQwMjg1MS8zMzkwODY0OTYtMTA4MTc0MDQtNzQ0Ny00ZDdmLTk0ZWMtMDNhM2ZjNjNlMjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAyMzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZWFlNWMyM2M2YjA4MzFmMjQ4ZjY3ZTE3NjQ5NTFiNWE4YWJkZWNlNmIwNTIwOTliNWViNmMwY2Y2YmI4YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d4TXqOxe45nwbL5qgA3o4x6dBLWo409An5MwTWTNFOk)
> 
> What is the tweak?

Hi its Ampere
![C1189082-3F1C-4923-B117-996AFDC438AD](https://github.com/opa334/Dopamine/assets/48402851/0e1227a5-9f97-4940-85bc-37e4b1a17153)

**Comment by luhgarlicbread** [comment] 2024-06-13 17:23
> You enable it the same way you disabled it, presumably

That would make sense. The only problem is, I have no idea how it was disabled.

**Comment by robi62** [comment] 2024-07-09 10:53
Suddenly after months battery is showing I have not changed anything
![E52A0ADE-9262-4DE4-8A10-E27B32552CAD](https://github.com/opa334/Dopamine/assets/48402851/de774b68-ff46-4634-98cf-945eea436e3d)

**Comment by 4193883-eng** [comment] 2024-07-10 14:03
> > > Hi before I jaibreak iphone 11 pro it was showing but since I jb not showing even in stock mode I am tempted to do a erase and reset and see But frightened to loose all tweaks
> > 
> > 
> > you probably just disabled a daemon or something, that can easily be undone without resetting your device.
> 
> How do we re-enable it?

use [geranium](https://github.com/c22dev/Geranium)!

**Comment by luhgarlicbread** [comment] 2024-07-10 14:45
> Suddenly after months battery is showing I have not changed anything
> ![E52A0ADE-9262-4DE4-8A10-E27B32552CAD](https://private-user-images.githubusercontent.com/48402851/346929679-de774b68-ff46-4634-98cf-945eea436e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjMwMzEsIm5iZiI6MTcyMDYyMjczMSwicGF0aCI6Ii80ODQwMjg1MS8zNDY5Mjk2NzktZGU3NzRiNjgtZmY0Ni00NjM0LTk4Y2YtOTQ1ZWVhNDM2ZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE0NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxN2U2OWZiZGQyNDliMDI4ZjE4NzU0Y2ZiMWEzMjA2ZDgzZTA5YmNkZTljZDdhNzkyM2I4MDhjOWQ2ODVjYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tqDl0CH1NZtUZsrJjXcsDrHLhy6qvOkoDUu8MRzuiMk)

bruh me too yea

**Comment by luhgarlicbread** [comment] 2024-07-25 22:19
> Suddenly after months battery is showing I have not changed anything
> ![E52A0ADE-9262-4DE4-8A10-E27B32552CAD](https://private-user-images.githubusercontent.com/48402851/346929679-de774b68-ff46-4634-98cf-945eea436e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NDYyMzgsIm5iZiI6MTcyMTk0NTkzOCwicGF0aCI6Ii80ODQwMjg1MS8zNDY5Mjk2NzktZGU3NzRiNjgtZmY0Ni00NjM0LTk4Y2YtOTQ1ZWVhNDM2ZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDIyMTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NjQ1M2NiYjYxNjI5ZmUxNTMwY2Q5YTRmZTJiN2RiNzJiNmIzMDY1ZWM4ODQwNGNhZGJjODliNTZkMmM4ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4tqquCRONLmFjqQxsSfGLJS2P3F_xKyFL91qfeYyz-Y)

Bruh it’s gone for me again 😂😂

**Comment by opa334** [comment] 2024-07-25 22:59
closing since this is clearly unrelated to dopamine

**Closed as not planned by opa334** 2024-07-25 22:59 UTC
