### ISSUE TITLE
About Signal  and Brightness issues

### ISSUE THREAD

**Issue by Upfunny** [opa334/Dopamine#247] opened 2023-08-18 02:09 UTC
When I use dopamine to jailbreak my iPhone 12 Pro Max running iOS 15.4.1, I encounter two issues:

Random occurrence: The auto-brightness feature fails, and the screen remains at the lowest brightness level. This can be resolved by “Restart SpringBoard” using dopamine, but the screen becomes very dim, making it difficult to see outdoors and operate the device.

Consistent occurrence: I am using China Telecom as my telecom carrier. After every successful jailbreak, I experience a loss of signal. “Restart SpringBoard” and “Reboot Userspace” do not resolve this issue. Only by removing and reinserting the SIM card can make it work.

**Comment by opa334** [comment] 2023-10-24 11:35
First one is duplicate of #123

Second one seems like stock bug.

**Closed by opa334** 2023-10-24 11:35 UTC
